name: CD

# This action builds FreeImage for various distributions, collects the resulting
# wheels, and publishes them to pypi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.8.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp3{6,8,9,10}-* pp*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

  deploy:
    needs: wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: True
          virtualenvs-in-project: True

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: ./dist/

      - name: Publish Wheels
        run : |
          poetry publish --username=__token__ --password=${{ secrets.PYPI_ACCOUNT }}
